services:
  moobie-time:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: moobie-time
    volumes:
      - ./config/:/app/config/
    environment:
      - LOG_LEVEL=DEBUG
    restart: unless-stopped